# Generated by Django 5.1.7 on 2025-03-13 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VestaRealty', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='unit_number',
        ),
        migrations.AddField(
            model_name='tenant',
            name='date_joined',
            field=models.DateTimeField(null=True),
        ),
    ]
