# Generated by Django 5.1.7 on 2025-03-15 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VestaRealty', '0004_property_owned_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='email',
        ),
        migrations.AddField(
            model_name='tenant',
            name='id_no',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='notes',
            field=models.TextField(null=True),
        ),
    ]
