# Generated by Django 5.1.7 on 2025-03-18 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VestaRealty', '0006_alter_tenant_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoices',
            name='balance_carried_down',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
