# Generated by Django 5.1.7 on 2025-03-19 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VestaRealty', '0008_invoices_month'),
    ]

    operations = [
        migrations.CreateModel(
            name='paid_invoices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('water_bills', models.DecimalField(decimal_places=2, max_digits=10)),
                ('electricity_bills', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mpesa_code', models.CharField(max_length=100)),
                ('month', models.DateField(auto_now_add=True, null=True)),
                ('balance_carried_down', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('notes', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paid_invoice', to='VestaRealty.invoices')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paid_tenant', to='VestaRealty.tenant')),
            ],
        ),
    ]
