# Generated by Django 5.1.7 on 2025-03-21 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VestaRealty', '0011_alter_invoices_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paid_invoices',
            name='month',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
