# Generated by Django 5.1.7 on 2025-03-31 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VestaRealty', '0012_alter_paid_invoices_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='password',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
