# Generated by Django 5.1.7 on 2025-03-31 14:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VestaRealty', '0013_tenant_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='password',
            field=models.CharField(default=uuid.UUID('963f68f7-03ac-454a-aae9-5d8b3b84c2c4'), max_length=200, null=True),
        ),
    ]
