# Generated by Django 5.1.7 on 2025-03-31 14:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VestaRealty', '0014_alter_tenant_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='password',
            field=models.CharField(default=uuid.UUID('deec9322-a02e-4ea1-b158-8b1643aefe12'), max_length=200, unique=True),
        ),
    ]
