# Generated by Django 5.1.7 on 2025-05-13 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VestaRealty', '0015_alter_tenant_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='password',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
